Artifact as folder
PowerShell/PSRelease pull request #33
Opened 2018-07-31 00:43 UTC by TravisEz13

@adityapatwardhan Please review

2018-07-31 17:03 UTC, adityapatwardhan approved these changes

2018-07-31 17:16 UTC, adityapatwardhan requested changes

2018-07-31 17:16 UTC, adityapatwardhan commented on dockerBasedBuild/dockerBasedBuild.common.psm1
> +    if ($BuildData.EnableFeature['ArtifactAsFolder'])
EnableFeature is not a hashtable, you cannot access by `key`. Maybe 
```Powershell
$BuildData.EnableFeature.Contains('ArtifactAsFolder')
```

2018-08-01 17:35 UTC, TravisEz13 commented
@adityapatwardhan  Can you review?

2018-08-01 17:54 UTC, adityapatwardhan approved these changes

2018-08-01 17:54 UTC, adityapatwardhan commented on dockerBasedBuild/dockerBasedBuild.common.psm1
> +}
Add newline

2018-08-01 22:55 UTC, merged